diplomski v3.0/PracenjeTijekaProjekta/Models/PracenjeProjekta/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracenjeTijekaProjekta.Models.PracenjeProjekta
{
    public class Project
    {
        [Key]
        public int Id { get; set; }
        public string UserId { get; set; }
        [Required]
        [DisplayName("Project name")]
        public string ProjectName { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public String Category { get; set; }
        public IEnumerable<SelectListItem> CategoryList { get; set; }
        [Required]
        [Range(1, 1000)]
        [RegularExpression("([1-9][0-9]*)",ErrorMessage ="Duration is integer.")] 
        [DisplayName("Duration(min)")]
        public int Duration { get; set; }
        [Required]
        [Range(1,1000)]
        [RegularExpression("([1-9][0-9]*)",ErrorMessage = "Number of people needs to be integer.")]
        [DisplayName("People")]
        public int? NumP { get; set; }
    }
}

diplomski v3.0/PracenjeTijekaProjekta/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PracenjeTijekaProjekta.Models.PracenjeProjekta;

namespace PracenjeTijekaProjekta.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Projects
        public ActionResult Index(string ProjectName)
        {
            if (User.IsInRole("Admin") || User.IsInRole("Student") || User.IsInRole("Project manager"))
            {
                int totalDurationOfProject = 0;
                ViewBag.projectName = ProjectName;
                if (ProjectName != null)
                {          
                    List<Project> project = db.Projects.Where(x => x.ProjectName == ProjectName).ToList();
                    foreach (var item in db.Projects.ToList())
                        if (ProjectName == item.ProjectName)
                        {
                            totalDurationOfProject += item.Duration;                           
                        }
                   
                    ViewBag.totalDuration = (totalDurationOfProject/60).ToString("0") + " hours";
                    return View(project);
                }
            }          
            return View();
        }
        
        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            //iz baze uzima sve kategorije i upisuje u dropdown definiran u view-u create
            Project model = new Project();
            model.CategoryList = new SelectList(db.Categories, "CategoryName", "CategoryName");
            return View(model);
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,Description,Category,Duration,NumP")] Project project, string ProjectName)
        {      
            project.UserId = User.Identity.Name;
            project.ProjectName = ProjectName;         
            ModelState["ProjectName"].Errors.Clear();
           
            try
            {
                if (ModelState.IsValid)
                {
                    db.Projects.Add(project);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { @ProjectName = project.ProjectName });
                }
            }
            catch(DataException e)
            {
                ModelState.AddModelError("", e.Message);

            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
       
            Project project = db.Projects.Find(id);

            if (project == null)
            {
                return HttpNotFound();
            }

            project.CategoryList = new SelectList(db.Categories, "CategoryName", "CategoryName");
            return View(project);
        }

        // POST: Projects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,Description,Category,Duration,NumP")] Project project, string ProjectName)
        {

            project.UserId = User.Identity.Name;
            project.ProjectName = ProjectName;
            ModelState["ProjectName"].Errors.Clear();
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { @ProjectName = project.ProjectName });
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index", new { @ProjectName = project.ProjectName });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

diplomski v3.0/PracenjeTijekaProjekta/Controllers/UsersProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PracenjeTijekaProjekta.Models;
using PracenjeTijekaProjekta.Models.PracenjeProjekta;
using PagedList;

namespace PracenjeTijekaProjekta.Controllers
{
    public class UsersProjectsController : Controller
    {
        private ProjectContext db = new ProjectContext();
        ApplicationDbContext context = new ApplicationDbContext();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, bool chboxPM = false)
        {
            if (!User.IsInRole("Admin") && !User.IsInRole("Student") && !User.IsInRole("Project manager"))
            {
                return View();
            }
            else
            {
                if (page == null)
                {
                    page = 1;
                }
                ViewBag.CurrentSort = sortOrder;
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                var projects = from x in db.UsersProjects select x;

                if (User.IsInRole("Admin"))
                {
                    if (chboxPM == true)
                        projects = projects.Where(x => x.ProjectManager == null);
                    ViewBag.isChecked = chboxPM;
                }
                else if (User.IsInRole("Project manager"))
                {
                    projects = projects.Where(x => x.ProjectManager == User.Identity.Name);
                    ApplicationUser user = context.Users.Where(u => u.UserName.Equals(User.Identity.Name, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                    ViewBag.UsersNameSurname = user.Name + " " + user.Surname + " Board";
                }
                else if (User.IsInRole("Student"))
                {
                    projects = projects.Where(x => x.UserId == User.Identity.Name);
                }
                if (!String.IsNullOrEmpty(searchString))
                {
                    projects = projects.Where(s => s.ProjectName.Contains(searchString));

                }
                switch (sortOrder)
                {
                    case "Date":
                        projects = projects.OrderBy(s => s.Date);
                        break;
                    case "date_desc":
                        projects = projects.OrderByDescending(s => s.Date);
                        break;
                    default:  
                        projects = projects.OrderBy(s => s.ProjectName);
                        break;
                }

                int pageSize = 6;
                int pageNumber = (page ?? 1);
                return View(projects.ToPagedList(pageNumber, pageSize));
            }
        }
       
        // GET: UsersProjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersProjects/Create     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,ProjectName")] UsersProject usersProject)
        {
            usersProject.UserId = User.Identity.Name;
            usersProject.Date = DateTime.Now;
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(User.Identity.Name, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            usersProject.UsersNameSurname = user.Name + " " + user.Surname;
            
            if (ModelState.IsValid)
            {                         
                db.UsersProjects.Add(usersProject);
                db.SaveChanges();           
                return RedirectToAction("Index");
            }
            
            return View(usersProject);
        }

        // GET: UsersProjects/Delete/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersProject usersProject = db.UsersProjects.Find(id);
            if (usersProject == null)
            {
                return HttpNotFound();
            }
            return View(usersProject);
        }
        // POST: UsersProjects/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UsersProject usersProject = db.UsersProjects.Find(id);
            db.UsersProjects.Remove(usersProject);
            List<Project> projectDetailsList = db.Projects.Where(u => u.ProjectName == usersProject.ProjectName).ToList();
            foreach (Project project in projectDetailsList)
            db.Projects.Remove(project);
            db.SaveChanges();           
            
            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersProject usrproject = db.UsersProjects.Find(id);
            if (usrproject == null)
            {
                return HttpNotFound();
            }
            return View(usrproject);
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

diplomski v3.0/PracenjeTijekaProjekta/Views/Projects/Create.cshtml
@model PracenjeTijekaProjekta.Models.PracenjeProjekta.Project

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/createProject.css" rel="stylesheet" />
<h2>Add new data for my project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group" style="margin-top:30px">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2", @style = "margin-left:-6%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker", @style = "margin-left:12%" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:4%" })
        </div>
    </div>

    <div class="form-group" style="margin-top:24px">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @style = "margin-left:5%" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:-3%"})
        </div>
    </div>

    <div class="form-group" style="margin-top:24px">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2", @style = "margin-left:-1%" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Category, Model.CategoryList, "Select category", new { @class = "btn btn-default dropdown-toggle", @style = "width: 100%; margin-left:6%" })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:-2%"})
        </div>
    </div>

    <div class="form-group" style="margin-top:24px">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @style = "margin-left:5%" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:-3%"})
        </div>
    </div>

    <div class="form-group" style="margin-top:24px">
        @Html.LabelFor(model => model.NumP, htmlAttributes: new { @class = "control-label col-md-2", @style = "margin-left:-3%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumP, new { htmlAttributes = new { @class = "form-control", @style = "margin-left:9%" } })
            @Html.ValidationMessageFor(model => model.NumP, "", new { @class = "text-danger" ,@style= "margin-top:5px; margin-left:1%"})
        </div>
    </div>

    <div class="form-group" style="margin-top:24px;margin-left:20%">
        <div class="col-md-offset-2 col-md-10" >
            <input type="submit" value="Submit" class="btn btn-default" style="padding:3%" />
        </div>
    </div>
</div>
}
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{

    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

diplomski v3.0/PracenjeTijekaProjekta/Views/Projects/Delete.cshtml
@model PracenjeTijekaProjekta.Models.PracenjeProjekta.Project

@{
    ViewBag.Title = "Delete";
}
<link href="~/Content/deleteUsersProjects.css" rel="stylesheet" />

<h3>Are you sure you want to delete selected data?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size:medium;margin-bottom:2%; margin-left:-3%">
            Date
        </dt>

        <dd style="margin-left:23%;">
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt style="font-size:medium;margin-bottom:2%; margin-left:-3%">
            Description
        </dt>

        <dd style="margin-left:23%;">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt style="font-size:medium;margin-bottom:2%; margin-left:-3%">
            Category
        </dt>

        <dd style="margin-left:23%;">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt style="font-size:medium;margin-bottom:2%; margin-left:-3%">
            Duration
        </dt>

        <dd style="margin-left:23%;">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt style="font-size:medium;margin-bottom:2%; margin-left:-3%">
            Number of people
        </dt>

        <dd style="margin-left:23%;">
            @Html.DisplayFor(model => model.NumP)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions " style="margin-left:10%; margin-bottom:3%; font-size:medium ">
            <input type="submit" value="Delete" class="btn btn-default" style="padding:2% 2% 2% 2%"/>
            @Html.ActionLink("Back to List", "Index", new { Model.ProjectName })
        </div>
    }
</div>

diplomski v3.0/PracenjeTijekaProjekta/Views/Projects/Details.cshtml
@model PracenjeTijekaProjekta.Models.PracenjeProjekta.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

diplomski v3.0/PracenjeTijekaProjekta/Views/Projects/Edit.cshtml
@model PracenjeTijekaProjekta.Models.PracenjeProjekta.Project

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/createProject.css" rel="stylesheet" />
<h2>Edit data</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group" style="margin-top:30px">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2", @style = "margin-left:-6%" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker", @style = "margin-left:12%" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:4%" })
            </div>
        </div>

        <div class="form-group" style="margin-top:24px">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @style = "margin-left:5%" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:-3%" })
            </div>
        </div>

        <div class="form-group" style="margin-top:24px">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2", @style = "margin-left:-1%" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category, Model.CategoryList, "Select category", new { @class = "btn btn-default dropdown-toggle", @style = "width: 100%; margin-left:6%" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:-2%" })
            </div>
        </div>

        <div class="form-group" style="margin-top:24px">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @style = "margin-left:5%" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:-3%" })
            </div>
        </div>

        <div class="form-group" style="margin-top:24px">
            @Html.LabelFor(model => model.NumP, htmlAttributes: new { @class = "control-label col-md-2", @style = "margin-left:-3%" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumP, new { htmlAttributes = new { @class = "form-control", @style = "margin-left:9%" } })
                @Html.ValidationMessageFor(model => model.NumP, "", new { @class = "text-danger", @style = "margin-top:5px; margin-left:1%" })
            </div>
        </div>

        <div class="form-group" style="margin-top:24px;margin-left:20%">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" style="padding:3%" />
            </div>
        </div>
    </div>
}
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{

    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

diplomski v3.0/PracenjeTijekaProjekta/Views/Projects/Index.cshtml
@model IEnumerable<PracenjeTijekaProjekta.Models.PracenjeProjekta.Project>

@if (User.IsInRole("Student"))
{
    <p>
        <a title="Add data" style="float:right; cursor: pointer" onclick="location.href = '@(Url.Action("Create", "Projects", new { ProjectName = ViewBag.projectName }))'">
            <img src="~/images/plus2.png" style="width:40px; height:40px;" />
        </a>
    </p>
}
<h3 style="text-align:center">@ViewBag.projectName</h3>
<br />

@if (User.IsInRole("Admin"))
{
    <table class="table">
        <tr style="background-color:#edac4e;color:black">
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumP)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumP)
                </td>
                <td>
                    <a style="cursor: pointer" title="Edit" onclick="location.href = '@(Url.Action("Edit", "Projects", new { id = item.Id, ProjectName = item.ProjectName}))'">
                        <img src="~/images/edit2.png" style="width:20px; height:20px;" />
                    </a>
                    <a title="Delete" onclick="location.href = '@(Url.Action("Delete", "Projects", new { id = item.Id }))'" style="padding-left:10px; cursor: pointer">
                        <img src="~/images/trash2.png" style="width:20px; height:20px;" />
                    </a>
                </td>
            </tr>
        }
            <tr>
                <th>
                    <img src="~/images/orangearrow.gif" style="width:10px; height:10px; margin-top:-2%;margin-left:-5%" /> @Html.ActionLink("Back to List", "Index", "UsersProjects")
                </th>
                <th></th>
                <th style="font-weight:800">Total duration</th>
                <th style="font-weight:800">
                    @ViewBag.totalDuration
                </th>
                <th></th>
                <th></th>
            </tr>
    </table>


}
else if (User.IsInRole("Student"))
{

    <table class="table">
        <tr style="background-color:#edac4e;color:black">
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumP)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumP)
                </td>
                <td>
                    <a style="cursor: pointer" title="Edit" onclick="location.href = '@(Url.Action("Edit", "Projects", new { id = item.Id, ProjectName = item.ProjectName}))'">
                        <img src="~/images/edit2.png" style="width:20px; height:20px;" />
                    </a>
                    <a title="Delete" onclick="location.href = '@(Url.Action("Delete", "Projects", new { id = item.Id }))'" style="padding-left:10px; cursor: pointer">
                        <img src="~/images/trash2.png" style="width:20px; height:20px;" />
                    </a>
                </td>
            </tr>

        }
        <tr>
            <th>
                <img src="~/images/orangearrow.gif" style="width:10px; height:10px; margin-top:-2%;margin-left:-5%" /> @Html.ActionLink("Back to List", "Index", "UsersProjects")
            </th>
            <th></th>
            <th style="font-weight:800">Total duration</th>
            <th style="font-weight:800">
                @ViewBag.totalDuration
            </th>
            <th></th>
            <th></th>
        </tr>
    </table>



}
else if (User.IsInRole("Project manager"))
{
    <table class="table">
        <tr style="background-color:#edac4e;color:black">
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumP)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumP)
                </td>
                <td>
                    <a style="cursor: pointer" title="Edit" onclick="location.href = '@(Url.Action("Edit", "Projects", new { id = item.Id, ProjectName = item.ProjectName}))'">
                        <img src="~/images/edit2.png" style="width:20px; height:20px;" />
                    </a>
                    <a title="Delete" onclick="location.href = '@(Url.Action("Delete", "Projects", new { id = item.Id }))'" style="padding-left:10px; cursor: pointer">
                        <img src="~/images/trash2.png" style="width:20px; height:20px;" />
                    </a>
                </td>
            </tr>
        }
        <tr>
            <th>
                <img src="~/images/orangearrow.gif" style="width:10px; height:10px; margin-top:-2%;margin-left:-5%" /> @Html.ActionLink("Back to List", "Index", "UsersProjects")
            </th>
            <th></th>
            <th style="font-weight:800">Total duration</th>
            <th style="font-weight:800">
                @ViewBag.totalDuration
            </th>
            <th></th>
            <th></th>
        </tr>
    </table>
}

@*<div>
    @Html.ActionLink("Back to List", "Index", "UsersProjects")
</div>*@