diplomski v3.0/PracenjeTijekaProjekta/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PracenjeTijekaProjekta.Models.PracenjeProjekta;

namespace PracenjeTijekaProjekta.Controllers
{
    public class CategoriesController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryName")] Categories category)
        {
            for (int i = 0; i < db.Categories.ToList().Count; i++)
                if (category.CategoryName == db.Categories.ToList()[i].CategoryName)
                {
                    ModelState.AddModelError("", "Category already exists");
                    return View();
                }
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryName")] Categories category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categories category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

diplomski v3.0/PracenjeTijekaProjekta/Controllers/RolesController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using PracenjeTijekaProjekta.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracenjeTijekaProjekta.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: Roles
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }



        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        [HttpPost]
        public ActionResult Create(IdentityRole role)
        {
            for (int i = 0; i < db.Roles.ToList().Count; i++)
                if (role.Name == db.Roles.ToList()[i].Name)
                {
                    ModelState.AddModelError("", "Role already exists");
                    return View();
                }
            try
            {
                if (ModelState.IsValid)
                {
                    db.Roles.Add(role);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                return View(role);
            }
            catch
            {
                ModelState.AddModelError("", "Role name is required");
                return View();
            }
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(string id)
        {
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        [HttpPost]
        public ActionResult Edit(IdentityRole role)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    db.Entry(role).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                return View(role);
            }
            catch
            {
                ModelState.AddModelError("", "Enter role name");
                return View(role);
            }
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(string id)
        {

            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost]
        public ActionResult Delete(IdentityRole myRole)
        {
            IdentityRole role = db.Roles.Find(myRole.Id);
            db.Roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

diplomski v3.0/PracenjeTijekaProjekta/Controllers/UsersProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PracenjeTijekaProjekta.Models;
using PracenjeTijekaProjekta.Models.PracenjeProjekta;
using PagedList;

namespace PracenjeTijekaProjekta.Controllers
{
    public class UsersProjectsController : Controller
    {
        private ProjectContext db = new ProjectContext();
        ApplicationDbContext context = new ApplicationDbContext();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, bool chboxPM = false)
        {
            if (!User.IsInRole("Admin") && !User.IsInRole("Student") && !User.IsInRole("Project manager"))
            {
                return View();
            }
            else
            {
                if (page == null)
                {
                    page = 1;
                }
                ViewBag.CurrentSort = sortOrder;
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                var projects = from x in db.UsersProjects select x;

                if (User.IsInRole("Admin"))
                {
                    if (chboxPM == true)
                        projects = projects.Where(x => x.ProjectManager == null);
                    ViewBag.isChecked = chboxPM;
                }
                else if (User.IsInRole("Project manager"))
                {
                    projects = projects.Where(x => x.ProjectManager == User.Identity.Name);
                    ApplicationUser user = context.Users.Where(u => u.UserName.Equals(User.Identity.Name, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                    ViewBag.UsersNameSurname = user.Name + " " + user.Surname + " Board";
                }
                else if (User.IsInRole("Student"))
                {
                    projects = projects.Where(x => x.UserId == User.Identity.Name);
                }
                if (!String.IsNullOrEmpty(searchString))
                {
                    projects = projects.Where(s => s.ProjectName.Contains(searchString));

                }
                switch (sortOrder)
                {
                    case "Date":
                        projects = projects.OrderBy(s => s.Date);
                        break;
                    case "date_desc":
                        projects = projects.OrderByDescending(s => s.Date);
                        break;
                    default:  
                        projects = projects.OrderBy(s => s.ProjectName);
                        break;
                }

                int pageSize = 6;
                int pageNumber = (page ?? 1);
                return View(projects.ToPagedList(pageNumber, pageSize));
            }
        }
       
        // GET: UsersProjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersProjects/Create     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,ProjectName")] UsersProject usersProject)
        {
            usersProject.UserId = User.Identity.Name;
            usersProject.Date = DateTime.Now;
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(User.Identity.Name, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            usersProject.UsersNameSurname = user.Name + " " + user.Surname;
            
            if (ModelState.IsValid)
            {                         
                db.UsersProjects.Add(usersProject);
                db.SaveChanges();           
                return RedirectToAction("Index");
            }
            
            return View(usersProject);
        }

        // GET: UsersProjects/Delete/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersProject usersProject = db.UsersProjects.Find(id);
            if (usersProject == null)
            {
                return HttpNotFound();
            }
            return View(usersProject);
        }
        // POST: UsersProjects/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UsersProject usersProject = db.UsersProjects.Find(id);
            db.UsersProjects.Remove(usersProject);
            List<Project> projectDetailsList = db.Projects.Where(u => u.ProjectName == usersProject.ProjectName).ToList();
            foreach (Project project in projectDetailsList)
            db.Projects.Remove(project);
            db.SaveChanges();           
            
            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersProject usrproject = db.UsersProjects.Find(id);
            if (usrproject == null)
            {
                return HttpNotFound();
            }
            return View(usrproject);
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

diplomski v3.0/PracenjeTijekaProjekta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-1.12.1.js"></script>
    <link href="~/Content/custom.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        #myNavigationBar {
            background: rgba(0, 0, 0, 0.75);
        }

        .navbar-nav li:hover, .navbar-nav li.active a, .navbar-nav li.dropdown:hover, .navbar-nav li.dropdown a:hover, .navbar-header a {
            background: rgba(200, 38, 133, 0.64);
        }
        .navbar-nav li.a{
            background: rgba(0, 0, 0, 0.65);
        }
        ul, li {
            background: transparent;
        }
            ul.dropdown-menu {
                background-color: rgba(0, 0, 0, 0.75);
            }
           
        
    </style>
</head>
<body>
    <div id="myNavigationBar" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">                   
                @if (User.IsInRole("Admin"))
                {
            <ul class="nav navbar-nav">

                <li>
                    <a href="@Url.Action("Index", "UsersProjects")">
                        <span>Projects</span>
                    </a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Roles
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index", "Roles")"><span>Roles</span></a></li>
                        <li><a href="@Url.Action("Create", "Roles")"><span>Create new role</span></a></li>
                        <li><a href="@Url.Action("AssignRole", "Admin")"><span>Assign role</span></a></li>
                    </ul>
                </li>
                
                    <li><a href="@Url.Action("Index", "Categories")"><span>Categories</span></a></li>
                    
            </ul>

                    <form method="get" class="navbar-form navbar-left" action="@Url.Action("Index", "UsersProjects")" role="search">
                        @using (Html.BeginForm("Index", "UsersProjects", FormMethod.Get))
                        {
                            //ako trenutni view nije UsersProjects/Index search se nece ni pojavljivati
                            if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "UsersProjects"
                                && HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Index")
                            {
                                <div class="form-group">
                                    @Html.TextBox("searchString", "", new { @class = "form-control", @placeholder = " Search project", @id = "searchInput"})
                                </div>
                                <div class="form-group">
                                    <div class=" col-md-12">
                                        <input type="submit" value="Search" class="form-control" style = "width:110%" />
                                    </div>
                                </div>
                            }
                        }
                    </form>
                }
                else if (User.IsInRole("Project manager"))
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="@Url.Action("Index", "UsersProjects")">
                                <span>Projects</span>
                            </a>
                        </li>
                    </ul>
                    <form method="get" class="navbar-form navbar-left" action="@Url.Action("Index", "UsersProjects")" role="search">
                        @using (Html.BeginForm("Index", "UsersProjects", FormMethod.Get))
                        {
                            //ako trenutni view nije UsersProjects/Index search se nece ni pojavljivati
                            if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "UsersProjects"
                                && HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Index")
                            {
                                <div class="form-group">
                                    @Html.TextBox("searchString", "", new { @class = "form-control", @placeholder = " Search project", @id = "searchInput" })
                                </div>
                                <div class="form-group">
                                    <div class=" col-md-12">
                                        <input type="submit" value="Search" class="form-control" style = "width:110%"/>
                                    </div>
                                </div>
                            }
                        }
                    </form>
                }
                else if (User.IsInRole("Student"))
                {
                    <ul class="nav navbar-nav" >
                        <li >
                            <a  href="@Url.Action("Index", "UsersProjects")">
                                <span >Projects</span>
                            </a>
                        </li>
                    </ul>
                    <form method="get" class="navbar-form navbar-left" action="@Url.Action("Index", "UsersProjects")" role="search">
                        @using (Html.BeginForm("Index", "UsersProjects", FormMethod.Get))
                        { 
                            //ako trenutni view nije UsersProjects/Index search se nece ni pojavljivati
                            if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "UsersProjects"
                                && HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Index")
                            {
                        <div class="form-group">
                            @Html.TextBox("searchString", "", new { @class = "form-control", @placeholder = " Search project", @id = "searchInput" })                        
                        </div>
                                <div class="form-group">
                                    <div class=" col-md-12">
                                        <input type="submit" value="Search" class="form-control" style = "width:110%" />
                                    </div>
                                </div>                             
                            }
                        }
                    </form>
                }
                    <div>@Html.Partial("_LoginPartial")</div> 
        </div>
    </div>
    <br />
    <div class="main-w3l">
        <div class="w3layouts-main">
            @RenderBody()
            <footer class="footer">
                <p> @DateTime.Now.Year - Lorena Šegvić</p>
            </footer>
        </div>
   </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>